### ISSUE TITLE
[Purchase Orders] Allow bulk movement of line-items 

### ISSUE THREAD

**Issue by LenWebel** [GuibelTechnology/TheCargoTracker#35]

**Comment by LenWebel** [comment]
This has been completed and requires testing.

**Comment by LenWebel** [comment]
Missed the mark on this one - @GuiGimenez rectified:

The task was to move line items to a shipment linked to the purchase order.

**Comment by GuiGimenez** [comment]
been deactivated for the time being, possibly no longer required, the functionality is not to move the line items between shipments instead of purchase orders
