### ISSUE TITLE
[Daily Shipping Report] Project id is null in the ShipmentPurchaseOrders which cause issue to generate the report

### ISSUE THREAD

**Issue by GuiGimenez** [GuibelTechnology/TheCargoTracker#38]
When adding an existing shipment to a purchase order the ProjectId column is not getting populated which causes an issue to search and then to generate the Daily Shipping Report

**Comment by GuiGimenez** [comment]
getting emails with no attachments

**Comment by LenWebel** [comment]
#worksonmycomputer test more

**Comment by GuiGimenez** [comment]
works in mine too, happy to close
