### ISSUE TITLE
Bulk-edit (Editfield) shipments not refreshed when adding existing shipments to a purchase order

### ISSUE THREAD

**Issue by LenWebel** [GuibelTechnology/TheCargoTracker#43]
the problem is we are passing a list to the bulk-edit modal that ls being generated when the view initialises once only ever for the life of that screen.
that list is not being updated when we add shipments to the purchase order.

1. Create a purchase order 
2. Create several line-items attached to that purchase order
3. Bulk edit line items - choose shipments - no shipments in dropdown👍
4. Close bulk edit,
5. Click on shipments child view in the purchase order screen and create several shipments
6. switch back to line items screen 
7. select a few line items to bulk edit
8. click on bulk edit
9. choose shipments -> no shipments 👎  🚫  🔥 
10. refresh entiire page hit F5
11. repeat from steps 8 - see shipments

**Comment by LenWebel** [comment]
1 solutoin would be to move the `getshipmentsbypurchaseorderid` service call to `constructEditFields` method

**Comment by GuiGimenez** [comment]
great details here, thanks @LenWebel 
it's been fixed and merged
